CREATE USER 'cisco'@'%' IDENTIFIED BY 'cisco'; 
GRANT ALL PRIVILEGES ON *.* TO 'cisco'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE test;
USE test;
CREATE TABLE user (
  ID VARCHAR(255) NOT NULL,
  PW VARCHAR(255) NOT NULL
);
